image: gradle:8.4

stages:
  - build
  - test

cache:
  paths:
    - .gradle/wrapper
    - .gradle/caches

build:
  stage: build
  script:
    - gradle build

test:
  stage: test
  script:
    - gradle test
