server:
  port: 8080
spring:
  application:
    name: users
  datasource:
    username: postgres
    password: 123
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/users
  jpa:
    properties:
      hibernate:
        default_schema: users_scheme

  liquibase:
    default-schema: users_scheme

springdoc:
  swagger-ui:
    path: /doc-ui
