server:
  port: 7777
  ssl:
    enabled: true
    key-store-type: JKS
    key-store: serverCerts/$SERVER.keystore.jks
    key-store-password: 123456
    protocol: TLS
    enabled-protocols: TLSv1.3

keycloak:
  uri: 'http://localhost:8080'
  realm: "users"

spring:
  application:
    name: users
  datasource:
    username: postgres
    password: 123
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/users?ssl=true&sslmode=require
  jpa:
    properties:
      hibernate:
        default_schema: users_scheme
  liquibase:
    default-schema: users_scheme
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8080/realms/users

springdoc:
  swagger-ui:
    path: /doc-ui
