version: '3.7'
services:
  keycloak:
    image: quay.io/keycloak/keycloak:20.0.1
    container_name: keycloak-local
#    networks:
#      - keycloak-ldap
    environment:
      KEYCLOAK_ADMIN: 'admin'
      KEYCLOAK_ADMIN_PASSWORD: 'admin'
#      DB_VENDOR: 'h2'
#      KEYCLOAK_LOGLEVEL: "INFO"
#    volumes:
#      - ./imports/keycloak/realm-config.json:/tmp/example-realm.json
    command:
      - start-dev
    ports:
     - "8080:8080"

#  openldap:
#    image: rroemhild/test-openldap
#    container_name: ldap-local
#    networks:
#      - keycloak-ldap
#    ports:
#      - "10389:10389"
#      - "10636:10636"

#networks:
#  keycloak-ldap:
